name: Deploy IIoT Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (DS, DT, PD)'
        required: true
        default: 'DS'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group (if not exists)
        run: |
          env_lower=$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')
          az group create \
            --name rg-iiot-$env_lower \
            --location eastus

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-iiot-${{ github.event.inputs.environment }}
          template: ./main.bicep
          parameters: ./parameters.${{ github.event.inputs.environment }}.json
          failOnStdErr: false
