name: Deploy IIoT Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (DS, DT, PD)'
        required: true
        default: 'DS'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Convert environment to lowercase
        id: env
        run: |
          echo "env_lower=$(echo '${{ github.event.inputs.environment }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Create Resource Group (if not exists)
        run: |
          az group create \
            --name rg-iiot-${{ env.env_lower }} \
            --location southeastasia

      - name: Verify Bicep files
        run: |
          echo "Current directory: $(pwd)"
          ls -R infra

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-iiot-${{ github.event.inputs.environment }}
          template: ./infra/main.bicep
          parameters: ./infra/parameters.${{ env.env_lower }}.json
          failOnStdErr: false
