name: Deploy IIoT Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (DS, DT, PD)'
        required: true
        default: 'DS'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Convert environment to lowercase
        run: |
          echo "env_lower=$(echo '${{ github.event.inputs.environment }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 🧱 Lint Bicep files
      - name: Lint Bicep Templates
        run: |
          echo "Running bicep lint..."
          # Install Bicep CLI
          az bicep install
          # Lint all bicep files under infra folder
          find ./infra -name "*.bicep" -print0 | while IFS= read -r -d '' file; do
            echo "Linting $file"
            az bicep build --file "$file" --stdout >/dev/null
            az bicep lint --file "$file"
          done

      - name: Create Resource Group
        run: |
          az group create \
            --name rg-iiot-${{ env.env_lower }} \
            --location southeastasia

      - name: Validate Bicep
        run: |
          az deployment group validate \
            --resource-group rg-iiot-${{ env.env_lower }} \
            --template-file ./infra/main.bicep \
            --parameters ./infra/parameters.${{ env.env_lower }}.json

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --name iiot-deploy-${{ env.env_lower }} \
            --resource-group rg-iiot-${{ env.env_lower }} \
            --template-file ./infra/main.bicep \
            --parameters ./infra/parameters.${{ env.env_lower }}.json
